# Generated by Django 5.1.6 on 2025-02-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailystatistic',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='dailystatistic',
            unique_together=set(),
        ),
    ]
